spring: 
  profiles:
    active: production

  datasource:
    type: org.postgresql.ds.PGSimpleDataSource
    jdbcUrl: jdbc:postgresql://localhost:5432/general_testing
    username: postgres
    password: postgres

  jpa: 
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
